import Head from "next/head";

//components imports
import Header from "@/components/Header";
import Nav from "@/components/Nav";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/hulu.png" />
      </Head>
      <Header />
      <Nav />
    </div>
  );
}
